"""
scripts/seed_data.py
Loads data/patients.json and data/compliance_rulebook.json into Postgres.
Deliberately does NOT load data/predictions.json into the predictions
table directly -- predictions must go through POST /predictions (see
scripts/run_pipeline_on_seed_data.py) so that Digital Compliance Twins
actually get generated by the agent pipeline, exactly as a real
prediction event would.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from backend.db.models import Patient, RulebookRow  # noqa: E402
from backend.db.session import SessionLocal  # noqa: E402

DATA_DIR = Path(__file__).resolve().parents[1] / "data"


def seed_patients(db):
    with open(DATA_DIR / "patients.json") as f:
        patients = json.load(f)

    inserted = 0
    for p in patients:
        if db.get(Patient, p["patient_id"]) is None:
            db.add(
                Patient(
                    patient_id=p["patient_id"],
                    age=p["age"],
                    symptoms=p["symptoms"],
                    scan_type=p["scan_type"],
                    relevant_history=p["relevant_history"],
                )
            )
            inserted += 1
    db.commit()
    print(f"Seeded {inserted} new patients ({len(patients)} total in file).")


def seed_rulebook(db):
    with open(DATA_DIR / "compliance_rulebook.json") as f:
        rb = json.load(f)

    existing = db.get(RulebookRow, 1)
    if existing is None:
        db.add(
            RulebookRow(
                id=1,
                approved_model_versions=rb["approved_model_versions"],
                minimum_confidence_threshold=rb["minimum_confidence_threshold"],
                high_risk_conditions_requiring_review=rb["high_risk_conditions_requiring_review"],
            )
        )
        db.commit()
        print("Seeded initial rulebook.")
    else:
        print("Rulebook already exists -- left untouched. Edit via PUT /rulebook instead.")


def main():
    db = SessionLocal()
    try:
        seed_patients(db)
        seed_rulebook(db)
    finally:
        db.close()


if __name__ == "__main__":
    main()
